### ISSUE TITLE
Cooling Threshold Temperature: Fahrenheit value passed instead of Celsius — affects Warm Water control

### ISSUE THREAD

**Issue by Nastras** [homebridge-plugins/homebridge-tado#169]
### Analysis

Description:
When using @homebridge-plugins/homebridge-tado (version 8.0.0) to control my Warm Water zone, the plugin passes a raw Fahrenheit value to HomeKit for the Cooling Threshold Temperature characteristic. This exceeds HomeKit’s allowed range (10–35°C) and triggers the following warning:

`This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 65 exceeded maximum of 35.`

### Expected Behavior

The plugin should convert the temperature from Fahrenheit to Celsius before passing it to HomeKit — or use the system’s native Celsius value directly.

### Steps To Reproduce

	1.	Install @homebridge-plugins/homebridge-tado v8.0.0
	2.	Configure and enable a HOT_WATER zone like above
	3.	Start Homebridge
	4.	Observe the warning in the logs

### Logs

```markdown
Jun 18 18:35:41 Ak-SHS-2 homebridge1392463: @homebridge-plugins/homebridge-tado This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 65 exceeded maximum of 35. See https://homebridge.io/w/JtMGR for more info.
```

### Configuration

```json
{
  "active": true,
  "id": 0,
  "name": "Warmwasser",
  "type": "HOT_WATER",
  "delaySwitch": false,
  "noBattery": false,
  "mode": "CUSTOM",
  "modeTimer": 30,
  "minValue": 30,
  "maxValue": 65,
  "easyMode": false,
  "openWindowSensor": false,
  "openWindowSwitch": false,
  "separateTemperature": false,
  "separateHumidity": false,
  "accTypeBoiler": "FAUCET",
  "boilerTempSupport": true
}
```

### Environment

	•	Plugin version: 8.0.0
	•	Node.js version: 22.16.0
	•	Homebridge version: 1.10.0
	•	Raspberry Pi 4 Model B Rev 1.1, Debian GNU/Linux 11 (bullseye)

### Process Supervisor

systemd

### Additional Context

Add an automatic Fahrenheit → Celsius conversion for any value passed to Cooling Threshold Temperature. Alternatively, expose a config option to force the plugin to use Celsius consistently.

Thank you for looking into this!

**Comment by Nastras** [comment]
@smart7324 It's been almost a year, so I was wondering if there's any chance the bug will be fixed?

**Comment by smart7324** [comment]
@Nastras I will have a look into this on the weekend.

**Comment by Nastras** [comment]
Great 💪. Thx!

**Comment by smart7324** [comment]
Thanks for the detailed report! I took a closer look at this and it turns out this is not a Fahrenheit/Celsius conversion issue – 65°C is a perfectly valid hot water temperature.

The actual cause is that the plugin was incorrectly trying to set a cooling temperature limit on hot water zones, which don't support cooling at all. HomeKit's cooling characteristic has a hard cap of 35°C, so any hot water target temperature above that triggered the warning.

This has been fixed and is available in the next update `v9.2.0` (will be released today). Feel free to update the plugin and close this issue if it resolves the problem for you!

**Comment by Nastras** [comment]
Hi,

First of all, thank you for taking the time to investigate and fix issue #169. The fix works well on my setup and I really appreciate the continued maintenance of this plugin.

While testing the fix, I noticed another inconsistency with HOT_WATER zones that have temperature support enabled.

Current behavior

My configuration:

{
  "type": "HOT_WATER",
  "boilerTempSupport": true,
  "accTypeBoiler": "FAUCET"
}

The UI allows selecting FAUCET as the accessory type, but after startup the plugin still creates a HeaterCooler service:

[TadoPlatform] Warmwasser Boiler: Adding HeaterCooler service

As a result, HomeKit shows the hot water device as a thermostat/heater with a temperature wheel instead of a faucet.

Additional problem

The plugin appears to apply the default HEATING HeaterCooler limits (5–25°C) to the HOT_WATER HeaterCooler service.

My hot water supports 30–65°C, and the plugin correctly documents that HOT_WATER devices use a 30–65°C range, but HomeKit logs:

Heating Threshold Temperature characteristic was supplied illegal value:
number 30 exceeded maximum of 25
Heating Threshold Temperature characteristic was supplied illegal value:
number 25 exceeded minimum of 30

Expected behavior

Either:

1. accTypeBoiler should be ignored or hidden when boilerTempSupport=true, because a temperature-controlled hot water device is always exposed as a HeaterCooler.

or

2. accTypeBoiler="FAUCET" should actually create a Faucet service even when temperature support is enabled.

Additionally, when a HOT_WATER device is exposed as HeaterCooler, the characteristic limits should use the documented HOT_WATER range (30–65°C) instead of the default HEATING range (5–25°C).

The current behavior is confusing because the UI suggests a Faucet accessory, but HomeKit always receives a HeaterCooler service and generates invalid temperature range warnings.

Thanks again for looking into this. I hope the information above helps to reproduce the behavior.

<img width="1073" height="1536" alt="Image" src="https://github.com/user-attachments/assets/ae465d2c-418d-499a-8b56-0f303964f381" />
<img width="543" height="568" alt="Image" src="https://github.com/user-attachments/assets/57825817-5e2d-4b48-8eae-5228de211474" />
<img width="1073" height="1536" alt="Image" src="https://github.com/user-attachments/assets/956470b5-46f7-4c2c-b9de-4d2e466334b0" />
<img width="949" height="1825" alt="Image" src="https://github.com/user-attachments/assets/d3c0891c-34ad-431f-ae1b-9ac7a71b9f24" />
<img width="1590" height="899" alt="Image" src="https://github.com/user-attachments/assets/92713d94-3916-43c1-9c1f-8dae9952b874" />

**Comment by smart7324** [comment]
Hi, thank you for the detailed report!
I've just released `v9.2.1` which includes the following fixes related to your issue:

- Fixed an edge case where an unset or zero minValue/maxValue in the config could incorrectly override the HeaterCooler temperature limits, causing HOT_WATER zones to use the wrong range
- accTypeBoiler is now hidden in the UI when boilerTempSupport is enabled, since temperature-controlled hot water devices are always exposed as a HeaterCooler — this avoids the confusing combination that triggered this issue in the first place

Regarding the 5–25°C limit: I couldn't fully reproduce where these exact values came from in your setup – the fix I made addresses a known edge case with unset config values, but I'm not 100% certain that's the root cause in your case. Since HomeKit caches characteristic values, the old incorrect limits may still be stored even after the update. Please try the following after updating to v9.2.1:

1. In the Homebridge UI, go to Settings → Remove Single Cached Accessory
2. Select the affected HOT_WATER accessory
3. Restart Homebridge

If that doesn't resolve it, you can also try unpairing and re-pairing just the Tado child bridge in the Home app – this won't affect your other Homebridge accessories.

If you still see incorrect temperature limits after that, please enable debug mode in the plugin config and share the logs on startup, that will help me trace exactly where the values are coming from.

**Comment by Nastras** [comment]
Hi,

I updated to v9.2.1 and removed the affected HOT_WATER accessory from the Homebridge cache, then restarted the Tado child bridge.

Unfortunately, the issue still occurs.

Even though I have accTypeBoiler set to FAUCET, the accessory is still exposed as a Heater/HeaterCooler. I understand from your previous explanation that this may now be expected when boilerTempSupport is enabled.

However, the main problem remains: when I turn the hot water accessory off in HomeKit and then try to turn it back on, the plugin sends an invalid request to the Tado API.

The log shows that the zone ID is undefined:

PUT https://my.tado.com/api/v2/homes/xxxxxx/zones/undefined/overlay

It also seems to send a target temperature of 20°C:

Warmwasser Boiler: Temperature: 20

But the Tado API correctly rejects this because my hot water zone only supports 30–65°C:

temperature not in supported range [30–65°C, 86–149°F]

My current HOT_WATER config is:

{
  "active": true,
  "name": "Warmwasser",
  "delaySwitch": false,
  "autoOffDelay": false,
  "openWindowSensor": false,
  "openWindowSwitch": false,
  "separateTemperature": false,
  "separateHumidity": false,
  "mode": "CUSTOM",
  "modeTimer": 30,
  "easyMode": false,
  "noBattery": false,
  "type": "HOT_WATER",
  "boilerTempSupport": true,
  "accTypeBoiler": "FAUCET"
}

So it looks like there may still be two separate issues:

1. The HOT_WATER zone ID is not resolved correctly and becomes undefined.
2. When turning the accessory back on, HomeKit/plugin uses 20°C instead of restoring or sending a valid hot water temperature within 30–65°C.

Please let me know if you need debug startup logs. I can enable debug mode and provide them.

**Comment by Nastras** [comment]
[06/06/2026, 20:03:12] Homebridge v2.1.0 (HAP v2.1.7) (Tado) is running on port 57092.
[06/06/2026, 20:03:16] [TadoPlatform] tado API counter: 15,219

[06/06/2026, 20:12:22] [TadoPlatform] Child bridge restarting...
[06/06/2026, 20:12:22] Got SIGTERM, shutting down child bridge process...
[06/06/2026, 20:12:27] [TadoPlatform] Child bridge ended (code 143, signal null).
[06/06/2026, 20:12:27] [TadoPlatform] Child bridge starting (pid 115905)...

[06/06/2026, 20:12:28] Registering platform '@homebridge-plugins/homebridge-tado.TadoPlatform'
[06/06/2026, 20:12:28] [TadoPlatform] Child bridge started successfully (plugin v9.2.1).

[06/06/2026, 20:12:28] Loaded 9 cached accessories from cachedAccessories.0E42DB30628A.

[06/06/2026, 20:12:28] [TadoPlatform] Badezimmer Heater: Configuring accessory...
[06/06/2026, 20:12:28] [TadoPlatform] Kinderzimmer Heater: Configuring accessory...
[06/06/2026, 20:12:28] [TadoPlatform] Küche Heater: Configuring accessory...
[06/06/2026, 20:12:28] [TadoPlatform] Schlafzimmer Heater: Configuring accessory...
[06/06/2026, 20:12:28] [TadoPlatform] Wohnzimmer Heater: Configuring accessory...
[06/06/2026, 20:12:28] [TadoPlatform] Central Switch: Configuring accessory...
[06/06/2026, 20:12:28] [TadoPlatform] JP iPhone: Configuring accessory...
[06/06/2026, 20:12:28] [TadoPlatform] DP iPhone: Configuring accessory...
[06/06/2026, 20:12:28] [TadoPlatform] Anyone: Configuring accessory...

[06/06/2026, 20:12:28] [TadoPlatform] Warmwasser Boiler: Configuring new accessory...
[06/06/2026, 20:12:28] [TadoPlatform] Warmwasser Boiler: Adding HeaterCooler service

Before MINSTEP: undefined Warmwasser Boiler
After MINSTEP: 1 Warmwasser Boiler

[Warmwasser Boiler@Warmwasser Boiler@Heating Threshold Temperature] characteristic was supplied illegal value: number 30 exceeded maximum of 25

[Warmwasser Boiler@Warmwasser Boiler@Heating Threshold Temperature] characteristic was supplied illegal value: number 25 exceeded minimum of 30

[06/06/2026, 20:12:28] Homebridge v2.1.0 (HAP v2.1.7) (Tado) is running on port 57092.
[06/06/2026, 20:12:32] [TadoPlatform] tado API counter: 15,281

[06/06/2026, 20:16:54] [TadoPlatform] Warmwasser Boiler: State: 0

[06/06/2026, 20:17:00] [TadoPlatform] Warmwasser Boiler: Temperature: 20

[06/06/2026, 20:17:00] [TadoPlatform] {"method":"PUT","url":"https://my.tado.com/api/v2/homes/xxxxxx/zones/undefined/overlay","message":"Request failed with status code 422 (Unprocessable Entity)","statusCode":422,"body":{"errors":[{"code":"setting.notSupported","title":"temperature not in supported range [30–65°C, 86–149°F]"}]}}

[06/06/2026, 20:17:00] [TadoPlatform] Failed to set states: Request failed with status code 422 (Unprocessable Entity)

[06/06/2026, 20:17:12] [TadoPlatform] Warmwasser Boiler: Temperature: 20

[06/06/2026, 20:17:12] [TadoPlatform] {"method":"PUT","url":"https://my.tado.com/api/v2/homes/xxxxxx/zones/undefined/overlay","message":"Request failed with status code 422 (Unprocessable Entity)","statusCode":422,"body":{"errors":[{"code":"setting.notSupported","title":"temperature not in supported range [30–65°C, 86–149°F]"}]}}

[06/06/2026, 20:17:12] [TadoPlatform] Failed to set states: Request failed with status code 422 (Unprocessable Entity)

**Comment by smart7324** [comment]
Thanks for your detailed description and the logs. I need to look into this again on the weekend.

**Comment by smart7324** [comment]
Thanks again for the logs:)

I think I found the remaining issue. This was not the old cached `CoolingThresholdTemperature` problem anymore. The cache reset worked, and the logs show the hot water accessory was created again.

The problem was a combination of a few edge cases around temperature-controlled hot water zones:

- zone id `0` was not handled correctly in all places
- a resolved hot water zone id was not always written back to the boiler accessory context
- turning hot water back on from Apple Home could reuse the default `20°C` value, which is outside your supported `30–65°C` range
- the HeaterCooler temperature limits could be applied too late, causing the HomeKit range warnings during startup

This should be fixed in v9.3.0.

Please update to v9.3.0 and restart the tado child bridge.

You should not need another full cache reset. If Apple Home still shows stale values after the update, remove only the affected hot water accessory once and restart the child bridge again.

**Comment by Nastras** [comment]
Hi,

first of all, I would like to say a big thank you for your incredible support and for looking into this issue so quickly. I really appreciate the time and effort you put into fixing it.

I updated to v9.3.1 and I’m happy to report that the original issue seems to be fully resolved.

The hot water accessory can now be turned off and back on from Apple Home without the previous 422 API error. I also no longer see any requests to zones/undefined, and the temperature values now remain correctly within the supported 30–65°C range.

The only thing I still notice is that Apple Home shows 0.0°C as the current temperature for the hot water accessory, while the target temperature is displayed correctly, for example “heat to 65.0°C”.

Is this expected because HOT_WATER does not provide a real current temperature, or do you think there could be a better way to handle the HeaterCooler CurrentTemperature characteristic?

Again, a huge thank you for your fast responses, your detailed explanations, and the quick fixes across multiple releases. I really appreciate your work on this plugin and your support in getting this issue solved.

<img width="595" height="452" alt="Image" src="https://github.com/user-attachments/assets/a110dc90-154b-4271-b5c1-a44eb12f1a03" />

**Comment by smart7324** [comment]
Thanks again for reporting this.

After checking a few public tado API examples, it looks like tado does not provide `sensorDataPoints.insideTemperature` for `HOT_WATER` zones at all, or at least not reliably. The examples I found all show an empty `sensorDataPoints` object for `HOT_WATER` zones:

* https://github.com/homebridge-plugins/homebridge-tado/issues/18#issuecomment-485409419
* https://github.com/home-assistant/core/issues/7059
* https://shkspr.mobi/blog/2019/02/tado-api-guide-updated-for-2019/#hot-water-information
* https://community.smartthings.com/t/obsolete-tado-connect/65465/85

I’ve added a defensive fallback for `HOT_WATER` in v9.3.2: if tado provides a real insideTemperature, the plugin will use it. Otherwise it keeps the last known CurrentTemperature and falls back to the configured Hot Water target/minimum value, so HomeKit always receives a valid CurrentTemperature.

Can you see an actual current Hot Water temperature in the official tado app, or does the app only show the configured target temperature?

**Comment by Nastras** [comment]
Hi,

I checked the official tado app as requested.

It looks like the app does not display any actual hot water temperature. I can only see the configured target temperature (currently 65°C), both in the normal hot water view and in the schedule settings.

There is no information about a current water temperature such as 50°C or similar.

So your assumption seems to be correct: tado probably does not provide a real insideTemperature value for HOT_WATER zones.

Thanks again for investigating this and for continuously improving the HOT_WATER support. I really appreciate the effort you put into these fixes and the very quick responses.

<img width="1002" height="1342" alt="Image" src="https://github.com/user-attachments/assets/0c428932-4762-4994-ba3d-8a2bb8d45a3b" />

**Comment by smart7324** [comment]
Thanks for confirming! So I'm closing here as completed.

**Comment by Nastras** [comment]
Thank you so much for your outstanding support and the incredibly fast fixes.

I really appreciate the time and effort you invested in investigating this issue, explaining the root causes, and improving the HOT_WATER handling over several releases.

Everything is now working perfectly on my side. The hot water control, temperature range handling, zone ID handling, and the current temperature fallback are all working as expected.

Thanks again for maintaining this plugin and for the excellent support. It was a pleasure working with you to track down and solve these issues.

All the best and thanks again!

<img width="743" height="1668" alt="Image" src="https://github.com/user-attachments/assets/93ed165e-abab-4149-9b88-7bd00e17760c" />

**Comment by smart7324** [comment]
Gerne! Viel Spaß weiterhin mit dem Plugin:)

**Comment by Nastras** [comment]
Dankeschön 😂!
